apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - resource-quota.yaml
  - limit-range.yaml
  - local-queue.yaml
  - role-ray-user.yaml
  - rolebinding.yaml
  - scc-binding.yaml
  - sa-ray.yaml
  - sa-rolebinding.yaml
