apiVersion: v1
kind: LimitRange
metadata:
  name: ray-limits
  namespace: TENANT_NAMESPACE
spec:
  limits:
    - type: Container
      default:
        cpu: "2"
        memory: 4Gi
      defaultRequest:
        cpu: "100m"
        memory: 256Mi
      max:
        cpu: "8"
        memory: 32Gi
