apiVersion: v1
kind: Namespace
metadata:
  name: TENANT_NAMESPACE
  labels:
    opendatahub.io/dashboard: "true"
    kueue.openshift.io/managed: "true"
  annotations:
    openshift.io/description: "Ray workload namespace for TENANT_NAME"
