apiVersion: v1
kind: ResourceQuota
metadata:
  name: ray-quota
  namespace: TENANT_NAMESPACE
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 32Gi
    limits.cpu: "16"
    limits.memory: 64Gi
    requests.nvidia.com/gpu: "2"
    pods: "20"
